//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIShipwrecks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttractionType
    {
        public AttractionType()
        {
            this.Attractions = new HashSet<Attraction>();
        }
    
        public int ID { get; set; }
        public string AttractionType1 { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string Image { get; set; }
    
        public virtual ICollection<Attraction> Attractions { get; set; }
    }
}
