//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIShipwrecks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attraction
    {
        public Attraction()
        {
            this.AttractionContacts = new HashSet<AttractionContact>();
            this.AttractionLinks = new HashSet<AttractionLink>();
            this.AttractionPhotos = new HashSet<AttractionPhoto>();
        }
    
        public int ID { get; set; }
        public string AttractionName { get; set; }
        public Nullable<int> AttractionTypeID { get; set; }
        public Nullable<int> BodyOfWaterID { get; set; }
        public Nullable<int> TrailID { get; set; }
        public Nullable<int> YearBuilt { get; set; }
        public string Description { get; set; }
        public string NearestAddress { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public Nullable<int> ZipCode { get; set; }
        public bool OpenToPublic { get; set; }
        public bool HasWHSMooringBuoy { get; set; }
        public bool IsSnorkelable { get; set; }
        public bool HasWHSDiveGuide { get; set; }
        public bool HasTrailsSign { get; set; }
        public bool HasTrailsExhibit { get; set; }
        public bool IsNationalRegisterListed { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public bool HideRecord { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public bool MooringBuoyInPlace { get; set; }
        public Nullable<double> LatitudeDecimal { get; set; }
        public Nullable<double> LongitudeDecimal { get; set; }
    
        public virtual ICollection<AttractionContact> AttractionContacts { get; set; }
        public virtual ICollection<AttractionLink> AttractionLinks { get; set; }
        public virtual ICollection<AttractionPhoto> AttractionPhotos { get; set; }
        public virtual AttractionType AttractionType { get; set; }
        public virtual Trail Trail { get; set; }
        public virtual BodiesOfWater BodiesOfWater { get; set; }
    }
}
