//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIShipwrecks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CasualtyType
    {
        public CasualtyType()
        {
            this.Vessels = new HashSet<Vessel>();
        }
    
        public int ID { get; set; }
        public string CasualtyType1 { get; set; }
    
        public virtual ICollection<Vessel> Vessels { get; set; }
    }
}
