//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIShipwrecks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsArticle
    {
        public int ID { get; set; }
        public Nullable<int> NewspaperID { get; set; }
        public string Object { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Page { get; set; }
        public string Notes { get; set; }
        public string OtherSpelling { get; set; }
    
        public virtual Newspaper Newspaper { get; set; }
    }
}
