//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIShipwrecks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VesselPhoto
    {
        public int ID { get; set; }
        public int VesselID { get; set; }
        public string Caption { get; set; }
        public Nullable<int> PhotoSourceID { get; set; }
        public Nullable<int> PhotoTypeID { get; set; }
        public Nullable<System.DateTime> DateOfPhoto { get; set; }
        public string Image { get; set; }
        public string Thumb { get; set; }
    
        public virtual PhotoSource PhotoSource { get; set; }
        public virtual PhotoType PhotoType { get; set; }
        public virtual Vessel Vessel { get; set; }
    }
}
