//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIShipwrecks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vessel
    {
        public Vessel()
        {
            this.VesselPhotos = new HashSet<VesselPhoto>();
            this.VesselHistories = new HashSet<VesselHistory>();
            this.VesselVideos = new HashSet<VesselVideo>();
        }
    
        public int ID { get; set; }
        public Nullable<int> VesselTypeID { get; set; }
        public string VesselName { get; set; }
        public string ASINumber { get; set; }
        public Nullable<int> CasualtyTypeID { get; set; }
        public Nullable<System.DateTime> CasualtyDate { get; set; }
        public Nullable<int> VesselAge { get; set; }
        public string Owners { get; set; }
        public string HomePort { get; set; }
        public string Master { get; set; }
        public string CargoDescription { get; set; }
        public string LivesLost { get; set; }
        public string FormerNames { get; set; }
        public string RegistryNumber { get; set; }
        public string WhereBuilt { get; set; }
        public string Builder { get; set; }
        public string ContructionYear { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Breadth { get; set; }
        public Nullable<decimal> DepthOfHold { get; set; }
        public Nullable<decimal> GrossTonnage { get; set; }
        public Nullable<decimal> NetTonnage { get; set; }
        public string OMTonnage { get; set; }
        public Nullable<int> HullMaterialID { get; set; }
        public Nullable<int> PropulsionTypeID { get; set; }
        public Nullable<int> NumberOfMasts { get; set; }
        public Nullable<int> RigTypeID { get; set; }
        public string Engines { get; set; }
        public string Boilers { get; set; }
        public Nullable<int> Culture { get; set; }
        public bool CulturalMaterial { get; set; }
        public Nullable<int> DatingMethods { get; set; }
        public string SurveyDate { get; set; }
        public string SurveyPrincipleInvestigator { get; set; }
        public string ExcavatedDate { get; set; }
        public string ExcavationPrincipleInvestigator { get; set; }
        public Nullable<int> NationalRegisterStatusID { get; set; }
        public string NationalRegisterStatusNotes { get; set; }
        public Nullable<int> YearListedNationalRegister { get; set; }
        public bool Submerged { get; set; }
        public Nullable<int> WaterDepth { get; set; }
        public bool OnShoreline { get; set; }
        public string ConditionDescription { get; set; }
        public Nullable<int> PercentVesselPresent { get; set; }
        public bool WreckThreatened { get; set; }
        public string SiteName { get; set; }
        public Nullable<int> IDAccuracy { get; set; }
        public string CodeNumber { get; set; }
        public Nullable<int> BodyOfWaterID { get; set; }
        public Nullable<int> TrailID { get; set; }
        public string County { get; set; }
        public string NearestCity { get; set; }
        public Nullable<int> PACNumber { get; set; }
        public Nullable<int> LocationPotential { get; set; }
        public bool DiveAccessible { get; set; }
        public Nullable<int> NOAAChart { get; set; }
        public string TRS { get; set; }
        public string QuarterSections { get; set; }
        public string USGSQuad { get; set; }
        public Nullable<int> OwnerManagerAgencyID { get; set; }
        public Nullable<int> SturgeonBayStone { get; set; }
        public bool HasWHSMooringBuoy { get; set; }
        public bool HideLocationalInfo { get; set; }
        public string AccessDirections { get; set; }
        public bool HasWHSDiveGuide { get; set; }
        public string ChartImageFileName { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public bool HideRecord { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public bool MooringBuoyInPlace { get; set; }
        public bool Featured { get; set; }
        public Nullable<double> LatitudeDecimal { get; set; }
        public Nullable<double> LongitudeDecimal { get; set; }
        public string FeaturedPhoto { get; set; }
        public bool LocationKnown { get; set; }
    
        public virtual ICollection<VesselPhoto> VesselPhotos { get; set; }
        public virtual VesselType VesselType { get; set; }
        public virtual BodiesOfWater BodiesOfWater { get; set; }
        public virtual NationalRegisterStatus NationalRegisterStatus { get; set; }
        public virtual PercentVesselPresent PercentVesselPresent1 { get; set; }
        public virtual SturgeonBayStone SturgeonBayStone1 { get; set; }
        public virtual CasualtyType CasualtyType { get; set; }
        public virtual HullMaterial HullMaterial { get; set; }
        public virtual PropulsionType PropulsionType { get; set; }
        public virtual RigType RigType { get; set; }
        public virtual IDAccuracy IDAccuracy1 { get; set; }
        public virtual LocationPotential LocationPotential1 { get; set; }
        public virtual DatingMethod DatingMethod { get; set; }
        public virtual Culture Culture1 { get; set; }
        public virtual ICollection<VesselHistory> VesselHistories { get; set; }
        public virtual ICollection<VesselVideo> VesselVideos { get; set; }
    }
}
