//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIShipwrecks.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WIShipwrecksEntities : DbContext
    {
        public WIShipwrecksEntities()
            : base("name=WIShipwrecksEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AttractionContact> AttractionContacts { get; set; }
        public virtual DbSet<AttractionLink> AttractionLinks { get; set; }
        public virtual DbSet<AttractionPhoto> AttractionPhotos { get; set; }
        public virtual DbSet<Attraction> Attractions { get; set; }
        public virtual DbSet<AttractionType> AttractionTypes { get; set; }
        public virtual DbSet<BodiesOfWater> BodiesOfWaters { get; set; }
        public virtual DbSet<CasualtyType> CasualtyTypes { get; set; }
        public virtual DbSet<Contributor> Contributors { get; set; }
        public virtual DbSet<County> Counties { get; set; }
        public virtual DbSet<HullMaterial> HullMaterials { get; set; }
        public virtual DbSet<OwnerManagerAgency> OwnerManagerAgencies { get; set; }
        public virtual DbSet<PhotoSource> PhotoSources { get; set; }
        public virtual DbSet<PhotoType> PhotoTypes { get; set; }
        public virtual DbSet<PropulsionType> PropulsionTypes { get; set; }
        public virtual DbSet<RigType> RigTypes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Trail> Trails { get; set; }
        public virtual DbSet<Vessel_Contributors> Vessel_Contributors { get; set; }
        public virtual DbSet<VesselPhoto> VesselPhotos { get; set; }
        public virtual DbSet<Vessel> Vessels { get; set; }
        public virtual DbSet<VesselType> VesselTypes { get; set; }
        public virtual DbSet<NewsArticle> NewsArticles { get; set; }
        public virtual DbSet<Newspaper> Newspapers { get; set; }
        public virtual DbSet<NationalRegisterStatus> NationalRegisterStatus1 { get; set; }
        public virtual DbSet<PercentVesselPresent> PercentVesselPresents { get; set; }
        public virtual DbSet<SturgeonBayStone> SturgeonBayStones { get; set; }
        public virtual DbSet<Glossary> Glossaries { get; set; }
        public virtual DbSet<DatingMethod> DatingMethods { get; set; }
        public virtual DbSet<IDAccuracy> IDAccuracies { get; set; }
        public virtual DbSet<LocationPotential> LocationPotentials { get; set; }
        public virtual DbSet<Culture> Cultures { get; set; }
        public virtual DbSet<TimeFrame> TimeFrames { get; set; }
        public virtual DbSet<VesselHistory> VesselHistories { get; set; }
        public virtual DbSet<VesselVideo> VesselVideos { get; set; }
        public virtual DbSet<VideoSource> VideoSources { get; set; }
        public virtual DbSet<VideoType> VideoTypes { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<FeedbackRecipient> FeedbackRecipients { get; set; }
        public virtual DbSet<CurrentResearch> CurrentResearches { get; set; }
        public virtual DbSet<TechnicalFieldReport> TechnicalFieldReports { get; set; }
        public virtual DbSet<Calendar> Calendars { get; set; }
        public virtual DbSet<Link> Links { get; set; }
    }
}
